# STRINGS CHAPTER 3 

a = "Hello World" # double quotes string
b = 'Hello World' # single quotes string
c = '''Hello World''' # triple quotes string
d = """Hello World""" # triple quotes string

length = len(a) # length of string
# print(length)

name = "John Doe"

nameshort = name[0:4] # slicing string
print(nameshort)
character1 = name[-2]
print(character1) 

name3 = "harry"
print(name3[0:3])

print(name3[-4:-1]) # slicing string from -4 to -1
print(name3[1:4]) 